biomarkers = {
    "synonyms": {
        "TP53": [], 
        "PTEN": [], 
        "PD-L1": [], 
        "TMB": [], 
        "KRAS": [], 
        "BRAF": [], 
        "EGFR": [], 
        "KIT": [], 
        "PIK3CA":[], 
        "STK11": [], 
        "ALK":[], 
        "TERT":[], 
        "CDH1": [], 
        "ROS1": [], 
        "MET": [], 
        "RET": [], 
        "ERBB2": [], 
        'NTRK1':[], 
        'NTRK2': [], 
        'NTRK3': [], 
        'FGFR3': [], 
        'FGFR4':[]
    },
    "concept_codes": {
            'TP53': [
                        {'concept_code': '11998', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '21739-8', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '94217', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C118396', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C157238', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C158957', 'vocabulary_id': 'NCI'}
            ],
            'PTEN': [
                        {'concept_code': '9588', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '9588', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '9588', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': 'C121369', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C165569', 'vocabulary_id': 'CHAI_DYNAMIC_NCI'},
                        {'concept_code': 'C165569', 'vocabulary_id': 'CHAI_DYNAMIC_NCIM'}
            ],
            'PD-L1': [
                        {'concept_code': '83055-4', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '85147', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C122807', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C167384', 'vocabulary_id': 'NCI'}
            ],
            'TMB': [{'concept_code': 'LP410765-4', 'vocabulary_id': 'LOINC'}],
            'KRAS': [
                        {'concept_code': '21702-6', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '6407', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '6407', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': '6407', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '75974-6', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'LP19732-4', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'LP228807-6', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C41361', 'vocabulary_id': 'NCI'}
            ],
            'BRAF': [
                        {'concept_code': '1097', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': '1097', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '53844-7', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '58483-9', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '81705-6', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C107224', 'vocabulary_id': 'CHAI_DYNAMIC_SNOMED'},
                        {'concept_code': 'C107224', 'vocabulary_id': 'CHAI_DYNAMIC_NCI'},
                        {'concept_code': 'C98307', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C80273', 'vocabulary_id': 'NCI'}],
            'EGFR': [
                        {'concept_code': '21665-5', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '21666-3', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '3236', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '3236', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': '3236', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '55764-5', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '55769-4', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C126892', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C163018', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'C98357', 'vocabulary_id': 'NCI'},
                        {'concept_code': 'NP_005219:p.K29_N298insG', 'vocabulary_id': 'OMOP Extension'},
                        {'concept_code': 'NP_005219:p.L858R', 'vocabulary_id': 'OMOP Extension'},
                        {'concept_code': 'NP_005219:p.T790M', 'vocabulary_id': 'OMOP Extension'}
            ],
            'KIT': [
                        {'concept_code': '55201-8', 'vocabulary_id': 'LOINC'},
                        {'concept_code': 'C39712', 'vocabulary_id': 'NCI'}
            ],
            'PIK3CA': [
                        {'concept_code': '63419-6', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '83062-0', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '8975', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '8975', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '8975', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'}
            ],
            'STK11': [
                        {'concept_code': '53795-1', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '11389', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '11389', 'vocabulary_id': 'HGNC'},
                        {'concept_code': 'C128825', 'vocabulary_id': 'NCI'}
            ],
            'TERT': [
                        {'concept_code': '11730', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '11730', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '11730', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': 'C131104', 'vocabulary_id': 'NCI'}
            ],
            'CDH1': [
                        {'concept_code': '1748', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '1748', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '1748', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': '94240-9', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '94240-9', 'vocabulary_id': 'CHAI_DYNAMIC_LOINC'},
                        {'concept_code': 'C165503', 'vocabulary_id': 'CHAI_DYNAMIC_NCI'},
                        {'concept_code': 'C165503', 'vocabulary_id': 'CHAI_DYNAMIC_NCIM'}
            ],
            'ALK': [
                        {'concept_code': '427', 'vocabulary_id': 'OMOP Genomic'},
                        {'concept_code': '427', 'vocabulary_id': 'HGNC'},
                        {'concept_code': '427', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO'},
                        {'concept_code': '427', 'vocabulary_id': 'CHAI_DYNAMIC_HUGO/HGNC'},
                        {'concept_code': '78205-2', 'vocabulary_id': 'LOINC'},
                        {'concept_code': '78210-2', 'vocabulary_id': 'LOINC'}
            ],
            'ROS1':[
                        {"concept_code": "C18399", "vocabulary_id": "NCI"},
                        {"concept_code": "10261", "vocabulary_id": "HGNC"},
                        {"concept_code": "C130952","vocabulary_id": "NCI"}
            ],
            'MET': [
                        {"concept_code": "92906-7","vocabulary_id": "LOINC"},
                        {"concept_code": "C157251","vocabulary_id": "NCI"},
                        {"concept_code": "C39788","vocabulary_id": "NCI"},
                        {"concept_code": "7029", "vocabulary_id": "HGNC"},
                        {"concept_code": "100026-4", "vocabulary_id": "LOINC"}
            ],
            'RET': [
                        {"concept_code": "21734-9","vocabulary_id": "LOINC"},
                        {"concept_code": "21733-1","vocabulary_id": "LOINC"},
                        {"concept_code": "94224-3 ","vocabulary_id": "LOINC"},
                        {"concept_code": "C43293","vocabulary_id": "NCI"},
                        {"concept_code": "9967", "vocabulary_id": "HGNC"},
            ],
            'ERBB2':[{"concept_code":"42783-1","vocabulary_id": "LOINC"}],
            'NTRK1': [
                        {"concept_code": "8031","vocabulary_id": "HGNC"},
                        {"concept_code": "C153059","vocabulary_id": "NCI"},
                        {"concept_code": "C169007","vocabulary_id": "NCI"},
            ],
            'NTRK2': [
                        {"concept_code": "8032","vocabulary_id": "HGNC"},
                        {"concept_code": "C158054","vocabulary_id": "NCI"}
            ],
            'NTRK3': [
                        {"concept_code": "8033","vocabulary_id": "HGNC"},
                        {"concept_code": "C158054","vocabulary_id": "NCI"}
            ],
            'FGFR3': [{ "concept_code": "38413-1", "vocabulary_id": "LOINC"}],
            'FGFR4': [
                        {"concept_code": "3691","vocabulary_id": "HGNC"},
                        {"concept_code": "C84092","vocabulary_id": "NCI"}
            ]
        
        }
    }
imaging_codes = [
    {"ref_key":"Computed tomography","concept_code":"146281001","vocabulary_id":"SNOMED"},
    {"ref_key":"Computed tomography","concept_code":"LP6207-7","vocabulary_id":"LOINC"},
    {"ref_key":"Computed tomography","concept_code":"77477000","vocabulary_id":"SNOMED"},
    {"ref_key":"MRI with contrast","concept_code":"51619007","vocabulary_id":"SNOMED"},
    {"ref_key":"MRI without contrast","concept_code":"90084008","vocabulary_id":"SNOMED"},
    {"ref_key":"Magnetic resonance imaging","concept_code":"569..12","vocabulary_id":"Read"},
    {"ref_key":"Magnetic resonance imaging","concept_code":"113091000","vocabulary_id":"SNOMED"},
    {"ref_key":"Magnetic resonance imaging","concept_code":"10078223","vocabulary_id":"MDR"},
    {"ref_key":"Magnetic resonance imaging","concept_code":"10078223","vocabulary_id":"MDR"},
    {"ref_key":"Positron emission tomography","concept_code":"779221000000104","vocabulary_id":"SNOMED"},
    {"ref_key":"Positron emission tomography","concept_code":"57C..00","vocabulary_id":"Read"},
    {"ref_key":"Positron emission tomography","concept_code":"10036223","vocabulary_id":"MDR"},
    {"ref_key":"Positron emission tomography","concept_code":"10036223","vocabulary_id":"MDR"},
    {"ref_key":"Positron emission tomography","concept_code":"82918005","vocabulary_id":"SNOMED"},
    {"ref_key":"Positron emission tomography with computed tomography","concept_code":"450436003","vocabulary_id":"SNOMED"},
    {"ref_key":"Radioisotope scan of bone","concept_code":"41747008","vocabulary_id":"SNOMED"}
]

ecog_value_codes = [{'concept_code': '425389002',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 0'},
 {'concept_code': '422512005',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 1'},
 {'concept_code': '422894000',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 2'},
 {'concept_code': '423053003',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 3'},
 {'concept_code': '423237006',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 4'},
 {'concept_code': '423409001',
  'vocabulary_id': 'SNOMED',
  'ref_key': 'ECOG performance status - grade 5'}]

stage_group_mapper_codes = [
    { "concept_code" : "C150547", "vocabulary_id" : "NCI", "ref_key" : "Ann Arbor Stage IE" },
    { "concept_code" : "C150549", "vocabulary_id" : "NCI", "ref_key" : "Ann Arbor Stage IIIE" },
    { "concept_code" : "C150550", "vocabulary_id" : "NCI", "ref_key" : "Ann Arbor Stage IIIS" },
    { "concept_code" : "64202001", "vocabulary_id" : "SNOMED", "ref_key" : "Clinical stage IV E"},
    { "concept_code" : "myeloma_plasma_cell_disorder@2890@070", "vocabulary_id" : "NAACCR", 
                                                        "ref_key" : "Durie Salmon Stage IIIA"},
    { "concept_code" : "myeloma_plasma_cell_disorder@2890@080", "vocabulary_id" : "NAACCR", 
                                                        "ref_key" : "Durie Salmon Stage IIIB" },
    { "concept_code" : "C28064", "vocabulary_id" : "NCI", "ref_key" : "Extensive Stage" },
    { "concept_code" : "C96244", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage I" },
    { "concept_code" : "C96245", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IA" },
    { "concept_code" : "C96246", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IA1" },
    { "concept_code" : "C96247", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IA2" },
    { "concept_code" : "C96248", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IB" },
    { "concept_code" : "C96249", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IB1" },
    { "concept_code" : "C96250", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IB2" },
    { "concept_code" : "C162222", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IB3" },
    { "concept_code" : "C96251", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IC" },
    { "concept_code" : "C128099", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IC1" },
    { "concept_code" : "C128100", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IC2" },
    { "concept_code" : "C128101", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IC3" },
    { "concept_code" : "C96252", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage II" },
    { "concept_code" : "C96253", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIA" },
    { "concept_code" : "C162224", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIA2" },
    { "concept_code" : "C96254", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIB" },
    { "concept_code" : "C96255", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage III" },
    { "concept_code" : "C96256", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIA" },
    { "concept_code" : "C128102", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIA1" },
    { "concept_code" : "C128103", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIA1(i)" },
    { "concept_code" : "C128105", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIA2" },
    { "concept_code" : "C96257", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIB" },
    { "concept_code" : "C96258", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIC" },
    { "concept_code" : "C96259", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIC1" },
    { "concept_code" : "C96260", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IIIC2" },
    { "concept_code" : "C96261", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IV" },
    { "concept_code" : "C96262", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IVA" },
    { "concept_code" : "C96263", "vocabulary_id" : "NCI", "ref_key" : "FIGO Stage IVB" },
    { "concept_code" : "C70658", "vocabulary_id" : "NCI", "ref_key" : "ISS Stage I Plasma Cell Myeloma"},
    { "concept_code" : "C70659", "vocabulary_id" : "NCI", "ref_key" : "ISS Stage II Plasma Cell Myeloma"},
    { "concept_code" : "C70660", "vocabulary_id" : "NCI", "ref_key" : "ISS Stage III Plasma Cell Myeloma"},
    { "concept_code" : "C93281", "vocabulary_id" : "NCI", "ref_key" : "Late Stage"},
    { "concept_code" : "C28065", "vocabulary_id" : "NCI", "ref_key" : "Limited Stage" },
    { "concept_code" : "C141394", "vocabulary_id" : "NCI", "ref_key" : "RISS Stage I Plasma Cell Myeloma"},
    { "concept_code" : "C141395", "vocabulary_id" : "NCI", "ref_key" : "RISS Stage II Plasma Cell Myeloma"},
    { "concept_code" : "C141396", "vocabulary_id" : "NCI", "ref_key" : "RISS Stage III Plasma Cell Myeloma"},
    { "concept_code" : "C28051", "vocabulary_id" : "NCI", "ref_key" : "Stage 0" },
    { "concept_code" : "C27964", "vocabulary_id" : "NCI", "ref_key" : "Stage 0a" },
    { "concept_code" : "C27965", "vocabulary_id" : "NCI", "ref_key" : "Stage 0is" },
    { "concept_code" : "C28056", "vocabulary_id" : "NCI", "ref_key" : "Stage A" },
    { "concept_code" : "C28057", "vocabulary_id" : "NCI", "ref_key" : "Stage B" },
    { "concept_code" : "C28059", "vocabulary_id" : "NCI", "ref_key" : "Stage B2" },
    { "concept_code" : "C28060", "vocabulary_id" : "NCI", "ref_key" : "Stage C" },
    { "concept_code" : "C28061", "vocabulary_id" : "NCI", "ref_key" : "Stage D" },
    { "concept_code" : "C28062", "vocabulary_id" : "NCI", "ref_key" : "Stage D1" },
    { "concept_code" : "C27966", "vocabulary_id" : "NCI", "ref_key" : "Stage I" },
    { "concept_code" : "C7874", "vocabulary_id" : "NCI", "ref_key" : "Stage I Chronic Lymphocytic Leukemia" },
    { "concept_code" : "C27975", "vocabulary_id" : "NCI", "ref_key" : "Stage IA" },
    { "concept_code" : "C27983", "vocabulary_id" : "NCI", "ref_key" : "Stage IA1" },
    { "concept_code" : "C27984", "vocabulary_id" : "NCI", "ref_key" : "Stage IA2" },
    { "concept_code" : "C136485", "vocabulary_id" : "NCI", "ref_key" : "Stage IA3" },
    { "concept_code" : "C27976", "vocabulary_id" : "NCI", "ref_key" : "Stage IB" },
    { "concept_code" : "C28052", "vocabulary_id" : "NCI", "ref_key" : "Stage IB1" },
    { "concept_code" : "C28053", "vocabulary_id" : "NCI", "ref_key" : "Stage IB2" },
    { "concept_code" : "C27981", "vocabulary_id" : "NCI", "ref_key" : "Stage IC" },
    { "concept_code" : "C141199", "vocabulary_id" : "NCI", "ref_key" : "Stage IE" },
    { "concept_code" : "C28054", "vocabulary_id" : "NCI", "ref_key" : "Stage II" },
    { "concept_code" : "C7875", "vocabulary_id" : "NCI", "ref_key" : "Stage II Chronic Lymphocytic Leukemia" },
    { "concept_code" : "C27967", "vocabulary_id" : "NCI", "ref_key" : "Stage IIA" },
    { "concept_code" : "C95177", "vocabulary_id" : "NCI", "ref_key" : "Stage IIA1" },
    { "concept_code" : "C95178", "vocabulary_id" : "NCI", "ref_key" : "Stage IIA2" },
    { "concept_code" : "C27968", "vocabulary_id" : "NCI", "ref_key" : "Stage IIB" },
    { "concept_code" : "C27969", "vocabulary_id" : "NCI", "ref_key" : "Stage IIC" },
    { "concept_code" : "C141200", "vocabulary_id" : "NCI", "ref_key" : "Stage IIE" },
    { "concept_code" : "C27970", "vocabulary_id" : "NCI", "ref_key" : "Stage III" },
    { "concept_code" : "C7876", "vocabulary_id" : "NCI", "ref_key" : "Stage III Chronic Lymphocytic Leukemia" },
    { "concept_code" : "C27977", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIA" },
    { "concept_code" : "C139980", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIA1" },
    { "concept_code" : "C139981", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIA2" },
    { "concept_code" : "C27978", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIB" },
    { "concept_code" : "C27982", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIC" },
    { "concept_code" : "C95179", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIC1" },
    { "concept_code" : "C95180", "vocabulary_id" : "NCI", "ref_key" : "Stage IIIC2" },
    { "concept_code" : "C137676", "vocabulary_id" : "NCI", "ref_key" : "Stage IIID" },
    { "concept_code" : "C27971", "vocabulary_id" : "NCI", "ref_key" : "Stage IV" },
    { "concept_code" : "C8646", "vocabulary_id" : "NCI", "ref_key" : "Stage IV Chronic Lymphocytic Leukemia"},
    { "concept_code" : "C27979", "vocabulary_id" : "NCI", "ref_key" : "Stage IVA" },
    { "concept_code" : "C141344", "vocabulary_id" : "NCI", "ref_key" : "Stage IVA1" },
    { "concept_code" : "C141345", "vocabulary_id" : "NCI", "ref_key" : "Stage IVA2" },
    { "concept_code" : "C27980", "vocabulary_id" : "NCI", "ref_key" : "Stage IVB" },
    { "concept_code" : "C28055", "vocabulary_id" : "NCI", "ref_key" : "Stage IVC" },
    { "concept_code" : "C92207", "vocabulary_id" : "NCI", "ref_key" : "Stage Unknown" },
    { "concept_code" : "C95957", "vocabulary_id" : "NCI", "ref_key" : "Stage X" }
]


bm_positive_value_codes = [
    {"ref_key":"Gene Expression","concept_code":"D015870","vocabulary_id":"MeSH"},
    {"ref_key":"Yes","concept_code":"RxMedsforAmytrophicLateral_Yes","vocabulary_id":"PPI"},
    {"ref_key":"Yes","concept_code":"JacksonHindsAppointment_Yes","vocabulary_id":"PPI"},
    {"ref_key":"Positive","concept_code":"394424008","vocabulary_id":"SNOMED"},
    {"ref_key":"Yes","concept_code":"RxMedsforChronicLung_Yes","vocabulary_id":"PPI"},
    {"ref_key":"Yes","concept_code":"RxMedsforOtherHeadaches_Yes","vocabulary_id":"PPI"},
    {"ref_key":"Fusion","concept_code":"31883006","vocabulary_id":"SNOMED"},
    {"ref_key":"Yes","concept_code":"CherokeeHealthPatient_YesCherokeeHealthPatient","vocabulary_id":"PPI"},
    {"ref_key":"Yes","concept_code":"RxMedsforArthritis_Yes","vocabulary_id":"PPI"},
    {"ref_key":"High","concept_code":"12895","vocabulary_id":"CHAI_CUSTOM_CHAI_CUSTOM_LAB_OUTPUT"},
    {"ref_key":"Pathogenic Variant","concept_code":"C168799","vocabulary_id":"NCI"},
    {"ref_key":"Non-V600 BRAF Gene Mutation","concept_code":"C173449","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},
    {"ref_key":"Positive","concept_code":"10828008","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},
    {"ref_key":"Non-V600 BRAF Gene Mutation","concept_code":"C173449","vocabulary_id":"NCI"},
    {"ref_key":"Pathogenic Variant","concept_code":"C168799","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},
    {"ref_key":"BRAF V600 Mutation","concept_code":"C107224","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},
    {"ref_key":"Positive","concept_code":"10828019","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},
    {"ref_key":"Gene Expression","concept_code":"30505","vocabulary_id":"CHAI_CUSTOM_BIOMARKER_VARIANT_TYPE"},{"ref_key":"Positive","concept_code":"C17666","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Positive","concept_code":"10828014","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Positive","concept_code":"10828009","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Malignant","concept_code":"C14143","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"10828011","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Nonsense Mutation","concept_code":"C62198","vocabulary_id":"NCI"},{"ref_key":"Alteration","concept_code":"C28344","vocabulary_id":"NCI"},{"ref_key":"BRAF V600 Mutation","concept_code":"C107224","vocabulary_id":"CHAI_DYNAMIC_NCI"},{"ref_key":"High","concept_code":"C25227","vocabulary_id":"NCI"},{"ref_key":"Deleted","concept_code":"LA9047-7","vocabulary_id":"LOINC"},{"ref_key":"True","concept_code":"5467539","vocabulary_id":"OSM"},{"ref_key":"Yes","concept_code":"RxMedsforHypertension_Yes","vocabulary_id":"PPI"},{"ref_key":"Abnormal","concept_code":"LA12748-2","vocabulary_id":"LOINC"},{"ref_key":"Yes","concept_code":"AmytrophicLateralCurrently_Yes","vocabulary_id":"PPI"},{"ref_key":"EGFR Exon 20 Insertion Mutation","concept_code":"C125605","vocabulary_id":"NCI"},{"ref_key":"Deletion","concept_code":"C61330","vocabulary_id":"NCI"},{"ref_key":"Gene Amplification","concept_code":"C16605","vocabulary_id":"NCI"},{"ref_key":"Splice-Site Mutation","concept_code":"C19798","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"10828016","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Positive","concept_code":"1","vocabulary_id":"chai_biomarker_value"},{"ref_key":"Positive","concept_code":"10828007","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Messenger RNA Underexpression","concept_code":"50032","vocabulary_id":"CHAI_CUSTOM_TEST_RESULT"},{"ref_key":"True","concept_code":"LA14495-8","vocabulary_id":"LOINC"},{"ref_key":"A change in the amino acid residue at position 790 in the epidermal growth factor receptor protein where threonine has been replaced by methionine.","concept_code":"C98503","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"10828004","vocabulary_id":"SNOMED"},{"ref_key":"Yes","concept_code":"BaylorScott_Yes","vocabulary_id":"PPI"},{"ref_key":"Yes","concept_code":"HRHCare_Yes","vocabulary_id":"PPI"},{"ref_key":"True","concept_code":"1065","vocabulary_id":"CIEL"},{"ref_key":"Yes","concept_code":"LA33-6","vocabulary_id":"LOINC"},{"ref_key":"Nonsense Mutation","concept_code":"D018389","vocabulary_id":"MeSH"},{"ref_key":"Yes","concept_code":"373066001","vocabulary_id":"SNOMED"},{"ref_key":"EGFR Exon 19 Deletion Mutation","concept_code":"C126892","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"C25246","vocabulary_id":"NCI"},{"ref_key":"BRAF V600 Mutation","concept_code":"59294","vocabulary_id":"CHAI_CUSTOM_VARIANT_GROUPING"},{"ref_key":"Missense Mutation","concept_code":"C18133","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"ER POSITIVE","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"EGFR Exon 20 Insertion Mutation","concept_code":"59293","vocabulary_id":"CHAI_CUSTOM_VARIANT_GROUPING"},{"ref_key":"Deficiency","concept_code":"C94372","vocabulary_id":"NCI"},{"ref_key":"Messenger RNA Underexpression","concept_code":"C178118","vocabulary_id":"CHAI_DYNAMIC_NCI"},{"ref_key":"Positive","concept_code":"10828013","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Positive","concept_code":"10828018","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"High","concept_code":"LA9193-9","vocabulary_id":"LOINC"},{"ref_key":"Duplication","concept_code":"89049001","vocabulary_id":"SNOMED"},{"ref_key":"Gene Amplification","concept_code":"D005784","vocabulary_id":"MeSH"},{"ref_key":"Fusion","concept_code":"122501008","vocabulary_id":"SNOMED"},{"ref_key":"High","concept_code":"10020044","vocabulary_id":"MDR"},{"ref_key":"Variant of EGFR protein: Substitution in position 858 Leu replaced by Arg","concept_code":"NP_005219:p.L858R","vocabulary_id":"OMOP Extension"},{"ref_key":"Genetic mutation","concept_code":"55446002","vocabulary_id":"SNOMED"},{"ref_key":"Variant","concept_code":"40885006","vocabulary_id":"SNOMED"},{"ref_key":"Yes","concept_code":"RxMedsforPreDiabetes_Yes","vocabulary_id":"PPI"},{"ref_key":"True","concept_code":"C68850","vocabulary_id":"NCI"},{"ref_key":"Loss","concept_code":"C25559","vocabulary_id":"NCI"},{"ref_key":"Gene Expression","concept_code":"C16608","vocabulary_id":"NCI"},{"ref_key":"Likely Pathogenic Variant","concept_code":"C168800","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},{"ref_key":"Variant of EGFR protein: Substitution in position 858 Leu replaced by Arg","concept_code":"NP_005219:p.L858R","vocabulary_id":"CHAI_DYNAMIC_OMOP Extension"},{"ref_key":"Likely Pathogenic Variant","concept_code":"C168800","vocabulary_id":"NCI"},{"ref_key":"Genetic Fusion Positive","concept_code":"C177683","vocabulary_id":"NCI"},{"ref_key":"90%","concept_code":"LA15252-2","vocabulary_id":"LOINC"},{"ref_key":"Abnormal","concept_code":"263654008","vocabulary_id":"SNOMED"},{"ref_key":"High","concept_code":"1408","vocabulary_id":"CIEL"},{"ref_key":"Abnormal","concept_code":"85531003","vocabulary_id":"SNOMED"},{"ref_key":"Known","concept_code":"36692007","vocabulary_id":"SNOMED"},{"ref_key":"Yes","concept_code":"EauClaire_Yes","vocabulary_id":"PPI"},{"ref_key":"Positive","concept_code":"10828006","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Malignant","concept_code":"3","vocabulary_id":"CHAI_DYNAMIC_ICD-O-3"},{"ref_key":"Abnormal","concept_code":"C25401","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"10828017","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"High","concept_code":"13237","vocabulary_id":"CHAI_CUSTOM_TEST_RESULT"},{"ref_key":"Malignant","concept_code":"3","vocabulary_id":"CHAI_DYNAMIC_ICDO3"},{"ref_key":"Deletion","concept_code":"737543005","vocabulary_id":"SNOMED"},{"ref_key":"Gene amplification","concept_code":"12645001","vocabulary_id":"SNOMED"},{"ref_key":"Deficiency","concept_code":"246199000","vocabulary_id":"SNOMED"},{"ref_key":"Yes","concept_code":"EauClaireAppointment_Yes","vocabulary_id":"PPI"},{"ref_key":"Positive","concept_code":"393474000","vocabulary_id":"SNOMED"},{"ref_key":"Malignant","concept_code":"21594007","vocabulary_id":"SNOMED"},{"ref_key":"Yes","concept_code":"ArthritisCurrently_Yes","vocabulary_id":"PPI"},{"ref_key":"Yes","concept_code":"SpectrumHealthSitePairing_Yes        ","vocabulary_id":"PPI"},{"ref_key":"Variant of KRAS protein: Substitution in position 12 Gly replaced by Cys","concept_code":"NP_004976:p.G12C","vocabulary_id":"OMOP Extension"},{"ref_key":"Yes","concept_code":"SpectrumHealthSitePairing_Yes","vocabulary_id":"PPI"},{"ref_key":"Variant of KRAS protein: Substitution in position 12 Gly replaced by Cys","concept_code":"NP_004976:p.G12C","vocabulary_id":"CHAI_DYNAMIC_OMOP Extension"},{"ref_key":"BRAF V600E Mutation Present","concept_code":"C80275","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"ER Positive","vocabulary_id":"CHAI_DYNAMIC_ER Positive"},{"ref_key":"Mutation Abnormality","concept_code":"C45576","vocabulary_id":"NCI"},{"ref_key":"Known","concept_code":"C80137","vocabulary_id":"NCI"},{"ref_key":"Variant Pathogenic\\/Likely Pathogenic","concept_code":"C168803","vocabulary_id":"NCI"},{"ref_key":"Yes","concept_code":"C49488","vocabulary_id":"NCI"},{"ref_key":"Deletion","concept_code":"LA6692-3","vocabulary_id":"LOINC"},{"ref_key":"Yes","concept_code":"OtherHeadachesCurrently_Yes","vocabulary_id":"PPI"},{"ref_key":"Yes","concept_code":"JacksonHinds_Yes","vocabulary_id":"PPI"},
                           {"ref_key":"Yes","concept_code":"ChronicLungCurrently_Yes","vocabulary_id":"PPI"},{"ref_key":"Yes","concept_code":"CaliforniaUniversityCare_CaliforniaHealthCareYes","vocabulary_id":"PPI"},{"ref_key":"True","concept_code":"31874001","vocabulary_id":"SNOMED"},{"ref_key":"Positive","concept_code":"9c30.00","vocabulary_id":"Read"},{"ref_key":"Duplication","concept_code":"LA6686-5","vocabulary_id":"LOINC"},{"ref_key":"Variant","concept_code":"OMOP generated","vocabulary_id":"Concept Class"},{"ref_key":"High","concept_code":"75540009","vocabulary_id":"SNOMED"},{"ref_key":"Variant","concept_code":"variant","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_stagegroup"},{"ref_key":"Inframe Insertion","concept_code":"C165226","vocabulary_id":"CHAI_DYNAMIC_NCI"},{"ref_key":"Inframe Deletion","concept_code":"C165225","vocabulary_id":"CHAI_DYNAMIC_NCI"},{"ref_key":"Positive","concept_code":"10828005","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Positive","concept_code":"PR Positive","vocabulary_id":"CHAI_DYNAMIC_PR Positive"},{"ref_key":"EGFR Exon 18 Mutation","concept_code":"C128661","vocabulary_id":"NCI"},{"ref_key":"Hypermethylation","concept_code":"C20102","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"10828025","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"High","concept_code":"5","vocabulary_id":"CHAI_CUSTOM_LAB_OUTPUT"},{"ref_key":"EGFR Gene Alteration Positive","concept_code":"C157585","vocabulary_id":"NCI"},{"ref_key":"Positive","concept_code":"LA6576-8","vocabulary_id":"LOINC"},{"ref_key":"High","concept_code":"OMOP1019149","vocabulary_id":"RxNorm Extension"},{"ref_key":"Yes","concept_code":"CareAtHenryFord_YesCareAtHenryFord","vocabulary_id":"PPI"},{"ref_key":"Yes","concept_code":"PreDiabetesCurrently_Yes","vocabulary_id":"PPI"},{"ref_key":"Positive","concept_code":"10828026","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Malignant","concept_code":"C9305","vocabulary_id":"CHAI_DYNAMIC_ICDO3"},{"ref_key":"Positive","concept_code":"PR POSITIVE","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Frameshift Mutation","concept_code":"C17354","vocabulary_id":"NCI"},{"ref_key":"Amplification","concept_code":"C25418","vocabulary_id":"NCI"},{"ref_key":"Chromosomal Translocation","concept_code":"C3420","vocabulary_id":"NCI"},{"ref_key":"Chromosomal Translocation","concept_code":"50031","vocabulary_id":"CHAI_CUSTOM_BIOMARKER_VARIANT_TYPE"},{"ref_key":"Positive","concept_code":"10828010","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"}]

bm_negative_value_codes = [{"ref_key":"Normal","concept_code":"{normal}","vocabulary_id":"UCUM"},{"ref_key":"Low risk","concept_code":"723505004","vocabulary_id":"SNOMED"},{"ref_key":"Low","concept_code":"LA9194-7","vocabulary_id":"LOINC"},{"ref_key":"Negative","concept_code":"LA6577-6","vocabulary_id":"LOINC"},{"ref_key":"Negative","concept_code":"corpus_carcinoma@2890@000","vocabulary_id":"NAACCR"},{"ref_key":"Wild Type","concept_code":"C62195","vocabulary_id":"NCI"},{"ref_key":"Low","concept_code":"12896","vocabulary_id":"CHAI_CUSTOM_CHAI_CUSTOM_LAB_OUTPUT"},{"ref_key":"Negative","concept_code":"PR Negative","vocabulary_id":"CHAI_DYNAMIC_PR Negative"},{"ref_key":"Negative","concept_code":"ER NEGATIVE","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Negative","concept_code":"85696000","vocabulary_id":"SNOMED"},{"ref_key":"False","concept_code":"LA14496-6","vocabulary_id":"LOINC"},{"ref_key":"Low risk","concept_code":"LA19542-2","vocabulary_id":"LOINC"},{"ref_key":"Not detected","concept_code":"LA11883-8","vocabulary_id":"LOINC"},{"ref_key":"Negative","concept_code":"394426005","vocabulary_id":"SNOMED"},{"ref_key":"Equivocal","concept_code":"C86071","vocabulary_id":"NCI"},{"ref_key":"Negative","concept_code":"13250","vocabulary_id":"CHAI_CUSTOM_TEST_RESULT"},{"ref_key":"Low","concept_code":"C54722","vocabulary_id":"NCI"},{"ref_key":"Negative","concept_code":"corpus_sarcoma@2890@000","vocabulary_id":"NAACCR"},{"ref_key":"Low","concept_code":"62482003","vocabulary_id":"SNOMED"},{"ref_key":"Wild type","concept_code":"LA9658-1","vocabulary_id":"LOINC"},{"ref_key":"Negative","concept_code":"9c32.00","vocabulary_id":"Read"},{"ref_key":"Negative","concept_code":"393476003","vocabulary_id":"SNOMED"},{"ref_key":"BRAF Gene Mutation Negative","concept_code":"C148089","vocabulary_id":"NCI"},{"ref_key":"Low","concept_code":"low","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_mstage"},{"ref_key":"Normal","concept_code":"12894","vocabulary_id":"CHAI_CUSTOM_CHAI_CUSTOM_LAB_OUTPUT"},{"ref_key":"Equivocal","concept_code":"42425007","vocabulary_id":"SNOMED"},{"ref_key":"Equivocal","concept_code":"LA11885-3","vocabulary_id":"LOINC"},{"ref_key":"Low risk","concept_code":"3895@X2","vocabulary_id":"NAACCR"},{"ref_key":"Normal","concept_code":"126777","vocabulary_id":"OSM"},{"ref_key":"Equivocal","concept_code":"3854@2","vocabulary_id":"NAACCR"},{"ref_key":"Normal","concept_code":"4","vocabulary_id":"CHAI_CUSTOM_LAB_OUTPUT"},{"ref_key":"Variant Likely Benign","concept_code":"C168801","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},{"ref_key":"Equivocal","concept_code":"ER EQUIVOCAL","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Normal","concept_code":"C14165","vocabulary_id":"NCI"},{"ref_key":"Expression Negative","concept_code":"C165233","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},{"ref_key":"False","concept_code":"C68851","vocabulary_id":"NCI"},{"ref_key":"Low risk","concept_code":"low risk","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_stagegroup"},{"ref_key":"Genetic Fusion Negative","concept_code":"C177684","vocabulary_id":"NCI"},{"ref_key":"Variant Likely Benign","concept_code":"C168801","vocabulary_id":"NCI"},{"ref_key":"Expression Negative","concept_code":"C165233","vocabulary_id":"NCI"},{"ref_key":"Negative Finding","concept_code":"C38757","vocabulary_id":"NCI"},{"ref_key":"Benign","concept_code":"30807003","vocabulary_id":"SNOMED"},{"ref_key":"False","concept_code":"64100000","vocabulary_id":"SNOMED"},{"ref_key":"Benign","concept_code":"523@0","vocabulary_id":"NAACCR"},
                           {"ref_key":"False","concept_code":"1066","vocabulary_id":"CIEL"},{"ref_key":"Not detected","concept_code":"260415000","vocabulary_id":"SNOMED"},{"ref_key":"Negative","concept_code":"PR NEGATIVE","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Equivocal","concept_code":"4242500","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Negative","concept_code":"3","vocabulary_id":"chai_biomarker_value"},{"ref_key":"Gene Amplification Negative","concept_code":"C177681","vocabulary_id":"NCI"},{"ref_key":"Equivocal","concept_code":"PR EQUIVOCAL","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Negative","concept_code":"corpus_adenosarcoma@2890@000","vocabulary_id":"NAACCR"},{"ref_key":"Benign","concept_code":"LA6675-8","vocabulary_id":"LOINC"},{"ref_key":"Normal","concept_code":"17621005","vocabulary_id":"SNOMED"},{"ref_key":"Equivocal","concept_code":"PR Equivocal","vocabulary_id":"CHAI_DYNAMIC_PR Equivocal"},{"ref_key":"ALK Negative","concept_code":"C133707","vocabulary_id":"NCI"},{"ref_key":"EGFR Gene Mutation Negative","concept_code":"C148091","vocabulary_id":"NCI"},{"ref_key":"Low Threshold","concept_code":"C177366","vocabulary_id":"NCI"},{"ref_key":"Benign","concept_code":"0","vocabulary_id":"CHAI_DYNAMIC_ICDO3"},{"ref_key":"Negative","concept_code":"C25247","vocabulary_id":"NCI"},{"ref_key":"Benign","concept_code":"0","vocabulary_id":"CHAI_DYNAMIC_ICD-O-3"},{"ref_key":"Negative","concept_code":"260385009","vocabulary_id":"SNOMED"},{"ref_key":"Low","concept_code":"7045907","vocabulary_id":"OSM"},{"ref_key":"Normal","concept_code":"LA6626-1","vocabulary_id":"LOINC"},{"ref_key":"Negative","concept_code":"ER Negative","vocabulary_id":"CHAI_DYNAMIC_ER Negative"},{"ref_key":"Variant of Unknown Significance","concept_code":"C94187","vocabulary_id":"NCI"},{"ref_key":"Variant Benign","concept_code":"C168802","vocabulary_id":"NCI"},{"ref_key":"Variant Benign","concept_code":"C168802","vocabulary_id":"CHAI_DYNAMIC_SNOMED"},{"ref_key":"Benign","concept_code":"C14172","vocabulary_id":"NCI"},{"ref_key":"Low","concept_code":"7","vocabulary_id":"CHAI_CUSTOM_LAB_OUTPUT"},{"ref_key":"Equivocal","concept_code":"ER Equivocal","vocabulary_id":"CHAI_DYNAMIC_ER Equivocal"},{"ref_key":"Low risk","concept_code":"C102403","vocabulary_id":"CHAI_DYNAMIC_NCIT"}]
bm_unknown_value_codes = [{"ref_key":"Other","concept_code":"1514@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"plasma_cell_myeloma@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"180@9","vocabulary_id":"NAACCR"},{"ref_key":"5","concept_code":"LA10137-0","vocabulary_id":"LOINC"},{"ref_key":"Not applicable","concept_code":"754@999","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"970@88","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"plasma_cell_myeloma@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Regurgitation - no aspiration detected","concept_code":"398286002","vocabulary_id":"SNOMED"},{"ref_key":"Not applicable","concept_code":"lymphoma_cll_sll@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"OMOP332170","vocabulary_id":"RxNorm Extension"},{"ref_key":"Other","concept_code":"163@98","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"444@80","vocabulary_id":"NAACCR"},{"ref_key":"Complete","concept_code":"DPD120439","vocabulary_id":"DPD"},{"ref_key":"Complete","concept_code":"LA26032-5","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"501@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3650@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3645@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"7483@98","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1832@ZZU","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"261665006","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"R14.8","vocabulary_id":"ICD10CM"},{"ref_key":"Unknown","concept_code":"54690008","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"7481@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"444@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"primary_cutaneous_lymphoma_non_mf_ss@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Not Tested","concept_code":"C101887","vocabulary_id":"NCI"},{"ref_key":"Other","concept_code":"R19.8","vocabulary_id":"CHAI_DYNAMIC_ICD-10-CM"},{"ref_key":"Number","concept_code":"C25337","vocabulary_id":"NCI"},{"ref_key":"Unknown","concept_code":"261665006","vocabulary_id":"CHAI_DYNAMIC_ICDO3"},{"ref_key":"Postia","concept_code":"83235","vocabulary_id":"NCBIGENE"},{"ref_key":"Not applicable","concept_code":"1113@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3616@88","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3610@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1502@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"74964007","vocabulary_id":"SNOMED"},{"ref_key":"Not performed","concept_code":"160737","vocabulary_id":"CIEL"},{"ref_key":"Not applicable","concept_code":"mycosis_fungoides@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"primary_cutaneous_lymphoma_non_mf_ss@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1520@999","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3614@88","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"hemeretic@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"Generic-OT","vocabulary_id":"PCORNet"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"PPI"},{"ref_key":"Not applicable","concept_code":"lymphoma_cll_sll@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"ZYY","vocabulary_id":"NFC"},{"ref_key":"Unknown","concept_code":"3647@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"7480@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3097611000001100","vocabulary_id":"SNOMED"},{"ref_key":"Number","concept_code":"OMOP1014948","vocabulary_id":"RxNorm Extension"},{"ref_key":"Unknown","concept_code":"161@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3655@88","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3097611000001100","vocabulary_id":"dm+d"},{"ref_key":"Not applicable","concept_code":"plasma_cell_disorders@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_braf"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_surgery_claims"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_tstage"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"CHAI_DYNAMIC_emol_medications_medroute"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_line_of_therapy"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_nstage"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_brca2"},{"ref_key":"Not Reported","concept_code":"C43234","vocabulary_id":"NCI"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_pd-l1"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_c-met"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_her2"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_corona_virus_labs"},{"ref_key":"Inconclusive","concept_code":"13247","vocabulary_id":"CHAI_CUSTOM_TEST_RESULT"},{"ref_key":"Unknown","concept_code":"Unknown","vocabulary_id":"CHAI_CUSTOM_Ethnicity"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_brca1"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_tumor_exam"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_condition"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_egfr"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_progesterone_receptor"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_mstage"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_procedure_claims_test"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_kras"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_ecog"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_pd1"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_ros"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_estrogen_receptor"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_drug_exposure"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_alk"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_adverse_event"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_staging"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_line_of_therapy_standard"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_measurement"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_drug_regimen"},{"ref_key":"Other","concept_code":"other","vocabulary_id":"chai_procedure_claims"},{"ref_key":"Complete","concept_code":"e6299022-4a9d-4c20-ac65-6296c1089184","vocabulary_id":"SPL"},{"ref_key":"Complete","concept_code":"255594003","vocabulary_id":"SNOMED"},{"ref_key":"Not applicable","concept_code":"1170@9","vocabulary_id":"NAACCR"},{"ref_key":"Complete","concept_code":"OMOP1011288","vocabulary_id":"RxNorm Extension"},{"ref_key":"Other","concept_code":"460@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"759@8","vocabulary_id":"NAACCR"},{"ref_key":"Complete","concept_code":"91277000","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"1786@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"752@999","vocabulary_id":"NAACCR"},{"ref_key":"Number","concept_code":"LP18011-4","vocabulary_id":"LOINC"},{"ref_key":"5","concept_code":"421820001","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"3614@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1160@9","vocabulary_id":"NAACCR"},{"ref_key":"Not performed","concept_code":"LA7304-4","vocabulary_id":"LOINC"},{"ref_key":"Note","concept_code":"LP173418-7","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"1370@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1112@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1522@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"UNK","vocabulary_id":"Race"},{"ref_key":"Note","concept_code":"OMOP4822287","vocabulary_id":"Note Type"},{"ref_key":"Not applicable","concept_code":"plasma_cell_myeloma@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"LA46-8","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"Generic-UN","vocabulary_id":"PCORNet"},{"ref_key":"Other","concept_code":"1130@97","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"910@88","vocabulary_id":"NAACCR"},
                    {"ref_key":"Unknown","concept_code":"1512@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3200@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"mycosis_fungoides@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Intermediate","concept_code":"C73705","vocabulary_id":"NCI"},{"ref_key":"Other","concept_code":"787.99","vocabulary_id":"CHAI_DYNAMIC_ICD-9-CM"},{"ref_key":"Unknown","concept_code":"C80.9","vocabulary_id":"CHAI_DYNAMIC_ICD10CM"},{"ref_key":"Not applicable","concept_code":"hemeretic@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"lymphoma@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"plasma_cell_disorders@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3618@88","vocabulary_id":"NAACCR"},{"ref_key":"Complete","concept_code":"9668001000001102","vocabulary_id":"SNOMED"},{"ref_key":"Not applicable","concept_code":"3650@88","vocabulary_id":"NAACCR"},{"ref_key":"Specific site","concept_code":"260744002","vocabulary_id":"SNOMED"},{"ref_key":"Not applicable","concept_code":"hemeretic@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"LA4720-4","vocabulary_id":"LOINC"},{"ref_key":"Not applicable","concept_code":"3605@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3605@99","vocabulary_id":"NAACCR"},{"ref_key":"5","concept_code":"2024801000001106","vocabulary_id":"SNOMED"},{"ref_key":"Complete","concept_code":"1945a76e-6991-4e7a-b4e5-d6c097c46d8a","vocabulary_id":"SPL"},{"ref_key":"Not applicable","concept_code":"lymphoma@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"7484@98","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"LP75287-0","vocabulary_id":"LOINC"},{"ref_key":"Not applicable","concept_code":"1115@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"162@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"480@9","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1290@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3620@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1504@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"193@98","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"LP75287-0","vocabulary_id":"CHAI_DYNAMIC_LOINC"},{"ref_key":"Unknown","concept_code":"1847@ZZU","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1550@9","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3600@9","vocabulary_id":"NAACCR"},{"ref_key":"Probable diagnosis","concept_code":"2931005","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"161@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1150@9","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3624@9","vocabulary_id":"NAACCR"},{"ref_key":"Number","concept_code":"DPD126747","vocabulary_id":"DPD"},{"ref_key":"Not applicable","concept_code":"3645@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1067","vocabulary_id":"CIEL"},{"ref_key":"Other","concept_code":"1791@(60-98)","vocabulary_id":"NAACCR"},{"ref_key":"Not performed","concept_code":"262008008","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"1790@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1512@88","vocabulary_id":"NAACCR"},{"ref_key":"Note","concept_code":"LP72988-6","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"3312@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1524@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"160@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"7482@98","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"164@98","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"1524@98","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"163@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"193@99","vocabulary_id":"NAACCR"},{"ref_key":"Not Performed","concept_code":"C141477","vocabulary_id":"NCI"},{"ref_key":"Complete","concept_code":"C25250","vocabulary_id":"NCI"},{"ref_key":"Null","concept_code":"C47840","vocabulary_id":"NCI"},{"ref_key":"Unknown","concept_code":"7480@99","vocabulary_id":"NAACCR"},{"ref_key":"Complete","concept_code":"OMOP1011290","vocabulary_id":"RxNorm Extension"},{"ref_key":"Intermediate","concept_code":"11896004","vocabulary_id":"SNOMED"},{"ref_key":"Intermediate","concept_code":"LA16550-8","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"Z","vocabulary_id":"NFC"},{"ref_key":"Not applicable","concept_code":"385432009","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"162@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1114@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"LA24568-0","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"254@ZZU","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"7482@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"plasma_cell_disorders@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3646@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1514@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"primary_cutaneous_lymphoma_non_mf_ss@3843@8","vocabulary_id":"NAACCR"},{"ref_key":"Null","concept_code":"276727009","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"3310@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"150@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"830@99","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"52483-5","vocabulary_id":"LOINC"},{"ref_key":"Unknown","concept_code":"3300@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1944@ZZU","vocabulary_id":"NAACCR"},{"ref_key":"Intermediate","concept_code":"intermediate","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_stagegroup"},{"ref_key":"Other","concept_code":"198.89","vocabulary_id":"CHAI_DYNAMIC_ICD-9-CM"},{"ref_key":"Unknown","concept_code":"unknown","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_histgrade"},{"ref_key":"Unknown","concept_code":"C17998","vocabulary_id":"NCI"},{"ref_key":"Other","concept_code":"R06.09","vocabulary_id":"CHAI_DYNAMIC_ICD-10-CM"},{"ref_key":"5","concept_code":"34001005","vocabulary_id":"SNOMED"},{"ref_key":"Inconclusive","concept_code":"419984006","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"7483@99","vocabulary_id":"NAACCR"},{"ref_key":"Number","concept_code":"410680006","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"1540@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"mycosis_fungoides@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Note","concept_code":"34109-9","vocabulary_id":"LOINC"},{"ref_key":"Other","concept_code":"1420@1","vocabulary_id":"NAACCR"},{"ref_key":"Note","concept_code":"OMOP generated","vocabulary_id":"Domain"},{"ref_key":"Other","concept_code":"160@98","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"breast@2876@030","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1116@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3622@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"820@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1540@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3610@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"LA4489-6","vocabulary_id":"LOINC"},{"ref_key":"Note","concept_code":"{note}","vocabulary_id":"UCUM"},{"ref_key":"Unknown","concept_code":"164@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"UNKNOWN","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_histgrade"},{"ref_key":"5","concept_code":"5","vocabulary_id":"CHAI_DYNAMIC_Gleason Score"},{"ref_key":"Technical Problem","concept_code":"C49633","vocabulary_id":"NCI"},{"ref_key":"Other","concept_code":"C17649","vocabulary_id":"NCI"},{"ref_key":"5","concept_code":"5","vocabulary_id":"CHAI_DYNAMIC_emol_clinical_histgrade"},{"ref_key":"Insufficient Sample","concept_code":"C131121","vocabulary_id":"NCI"},{"ref_key":"Unknown","concept_code":"3626@9","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"170@9","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"756@999","vocabulary_id":"NAACCR"},{"ref_key":"5","concept_code":"L   5EX","vocabulary_id":"OXMIS"},{"ref_key":"Unknown","concept_code":"42894201","vocabulary_id":"SNOMED"},{"ref_key":"Other","concept_code":"1504@98","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"lymphoma_cll_sll@3844@8","vocabulary_id":"NAACCR"},{"ref_key":"Number","concept_code":"260299005","vocabulary_id":"SNOMED"},{"ref_key":"Postia","concept_code":"797942008","vocabulary_id":"SNOMED"},{"ref_key":"Unknown","concept_code":"1570@99","vocabulary_id":"NAACCR"},{"ref_key":"Inconclusive","concept_code":"LA9663-1","vocabulary_id":"LOINC"},{"ref_key":"Not applicable","concept_code":"760@8","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"450@9","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3655@99","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"2320@999999999","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"470@9","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"1140@7","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"7484@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"lymphoma@3845@8","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1130@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"3647@88","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"1783@9","vocabulary_id":"NAACCR"},{"ref_key":"Other","concept_code":"7481@98","vocabulary_id":"NAACCR"},{"ref_key":"Unknown","concept_code":"3646@99","vocabulary_id":"NAACCR"},{"ref_key":"Not applicable","concept_code":"1175","vocabulary_id":"CIEL"},{"ref_key":"Other","concept_code":"997.99","vocabulary_id":"CHAI_DYNAMIC_ICD-9-CM"},{"ref_key":"Note","concept_code":"C42619","vocabulary_id":"NCI"},{"ref_key":"Postia","concept_code":"797942008","vocabulary_id":"CHAI_DYNAMIC_SNOMEDCT"},{"ref_key":"Postia","concept_code":"797942008","vocabulary_id":"CHAI_DYNAMIC_SNOMED"}]