stage_group_mapper = {
    "Ann Arbor Stage IE": 1,
    "Ann Arbor Stage IIIE": 3,
    "Ann Arbor Stage IIIS": 3,
    "Clinical stage IV E": 4,
    "Durie Salmon Stage IIIA": 3,
    "Durie Salmon Stage IIIB": 3,
    "FIGO Stage I": 1,
    "FIGO Stage IA": 1,
    "FIGO Stage IA1": 1,
    "FIGO Stage IA2": 1,
    "FIGO Stage IB": 1,
    "FIGO Stage IB1": 1,
    "FIGO Stage IB2": 1,
    "FIGO Stage IB3": 1,
    "FIGO Stage IC": 1,
    "FIGO Stage IC1": 1,
    "FIGO Stage IC2": 1,
    "FIGO Stage IC3": 1,
    "FIGO Stage II": 2,
    "FIGO Stage IIA": 2,
    "FIGO Stage IIA2": 2,
    "FIGO Stage IIB": 2,
    "FIGO Stage III": 3,
    "FIGO Stage IIIA": 3,
    "FIGO Stage IIIA1": 3,
    "FIGO Stage IIIA1(i)": 3,
    "FIGO Stage IIIA2": 3,
    "FIGO Stage IIIB": 3,
    "FIGO Stage IIIC": 3,
    "FIGO Stage IIIC1": 3,
    "FIGO Stage IIIC2": 3,
    "FIGO Stage IV": 4,
    "FIGO Stage IVA": 4,
    "FIGO Stage IVB": 4,
    "Indeterminate": -1, 
    "ISS Stage I Plasma Cell Myeloma": 1,
    "ISS Stage II Plasma Cell Myeloma": 2,
    "ISS Stage III Plasma Cell Myeloma": 3,
    "Limited Stage": -1,
    "RISS Stage I Plasma Cell Myeloma": 1,
    "RISS Stage II Plasma Cell Myeloma": 2,
    "RISS Stage III Plasma Cell Myeloma": 3,
    "Stage 0": 0,
    "Stage 0a": 0,
    "Stage 0is": 0,
    "Stage A": 1,
    "Stage B": 2,
    "Stage B2": 2,
    "Stage C": 3,
    "Stage D": 4,
    "Stage D1": 4,
    "Stage I": 1,
    "Stage I Chronic Lymphocytic Leukemia": 1,
    "Stage IA": 1,
    "Stage IA1": 1,
    "Stage IA2": 1,
    "Stage IA3": 1,
    "Stage IB": 1,
    "Stage IB1": 1,
    "Stage IB2": 1,
    "Stage IC": 1,
    "Stage IE": 1,
    "Stage IS": 1,
    "Stage II": 2,
    "Stage II Chronic Lymphocytic Leukemia": 2,
    "Stage IIA": 2,
    "Stage IIA1": 2,
    "Stage IIA2": 2,
    "Stage IIB": 2,
    "Stage IIC": 2,
    "Stage IIE": 2,
    "Stage III": 3,
    "Stage III Chronic Lymphocytic Leukemia": 3,
    "Stage IIIA": 3,
    "Stage IIIA1": 3,
    "Stage IIIA2": 3,
    "Stage IIIB": 3,
    "Stage IIIC": 3,
    "Stage IIIC1": 3,
    "Stage IIIC2": 3,
    "Stage IIID": 3,
    "Stage IV": 4,
    "Stage IV Chronic Lymphocytic Leukemia": 4,
    "Stage IVA": 4,
    "Stage IVA1": 4,
    "Stage IVA2": 4,
    "Stage IVB": 4,
    "Stage IVC": 4,
    "Stage 1S": 1,
    "Stage Unknown": -1,
    "Stage X": -1
}


stage_mapper = {
	'X': -1,
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4
} 

ecog_grade_mapper = {
        "ECOG performance status - grade 0": 0, 
        "ECOG performance status - grade 1": 1, 
        "ECOG performance status - grade 2": 2,
        "ECOG performance status - grade 3": 3,
        "ECOG performance status - grade 4": 4
    }

bm_positive_value = ['Abnormal', 'Alteration', 'Chromosomal Translocation','Deleted', 'Deletion', 'Duplication', 'Frameshift Mutation', 'Fusion','Gene amplification', 'Gene Expression', 'Genetic Fusion Positive', 'Genetic mutation', 'High', 'Hypermethylation', 'Inframe Deletion', 'Inframe Insertion', 'Likely Pathogenic Variant', 'Malignant', 'Messenger RNA Underexpression', 'Missense Mutation', 
                     'Mutation Abnormality', 'Nonsense Mutation', 'Pathogenic Variant', 'Positive', 'Splice-Site Mutation',
                     'True', 'Variant',
                     'Variant Pathogenic/Likely Pathogenic', 'Yes',
                     'EGFR Exon 20 Insertion Mutation',
                     'EGFR Exon 19 Deletion Mutation',
                     'EGFR Exon 18 Mutation','BRAF V600 Mutation','Variant of KRAS protein: Substitution in position 12 Gly replaced by Cys','Loss',
                     'A change in the amino acid residue at position 790 in the epidermal growth factor receptor protein where threonine has been replaced by methionine.', 
                     'Non-V600 BRAF Gene Mutation','Deficiency','Amplification','EGFR Gene Alteration Positive','90%',
                     'BRAF V600E Mutation Present',
                     'Variant of EGFR protein: Substitution in position 858 Leu replaced by Arg','Known','Gene Amplification']

bm_negative_value = ['ALK Negative','Benign','Expression Negative','Gene Amplification Negative','Genetic Fusion Negative','Low','Low risk','Low Threshold','Negative','Negative Finding','Normal','Not detected','Variant Benign','Variant Likely Benign','Wild Type','Wild type','False','EGFR Gene Mutation Negative','BRAF Gene Mutation Negative','Equivocal','Variant of Unknown Significance']

bm_unknown_value = ['Not applicable','Null','Other','Specific site','Not Performed','Note','Not performed','Postia','Complete','Inconclusive','Number','Technical Problem','5','Not Reported','Intermediate','Insufficient Sample','Unknown','Not Tested','Probable diagnosis','Regurgitation - no aspiration detected']