- key: hemoglobin_in_blood
  description: 'Client: Janssen.  Internal Authors: Katrin Gemmler, Travis Stenerson, Yanina Natanzon.
                reference range from https://labtestsonline.org/tests/hemoglobin, linked from https://loinc.org/718-7/'
  synonyms:
    - hemoglobin
  codes:
    LOINC:
      - 718-7
  attributes:
    valid:
      min: 0.0
      max: 25.0
    reference:
      min: 14.0
      max: 17.5
    units: g/dl
    source: janssen 20210708

- key: wbc
  description: 'reference range taken from adult normal range as listed at https://labtestsonline.org/tests/white-blood-cell-count-wbc,
                linked from https://loinc.org/6690-2/'
  synonyms:
    - white blood
    - white blood cell
    - wbc count
  codes:
    LOINC:
      - 6690-2
      - 26464-8
      - 49498-9
      - 33256-9
      - 12227-5
      - 804-5

  attributes:
    valid:
      min: 0.0
      max: 1000.0
    reference:
      min: 4.5
      max: 11.0
    units: 1e3/mm3
    source: Sam's cardiac ae 20210708

- key: neutrophils_count
  description: 'reference range from https://www.mayocliniclabs.com/test-catalog/Clinical+and+Interpretive/9109'
  synonyms:
    - neutrophils
  codes:
    LOINC:
      - 26499-4
      - 751-8
      - 753-4
      - 768-2 #Added
      - 30451-9 #Added
  attributes:
    valid:
      min: 0.0
      max: 1000.0
    reference:
      min: 1.56
      max: 6.45
    units: 1e3/mm3
    source: rdas, canoble 20210708

- key: platelets
  description: 'reference range listed at the top of https://loinc.org/777-3/'
  synonyms:
    - platelets count
    - mean platelet volume
  codes:
    LOINC:
      - 777-3
      - 26515-7
  attributes:
    valid:
      min: 0.0
      max: 1000.0
    reference:
      min: 150.0
      max: 450.0
    units: 1e3/mm3
    source: Sam's cardiac ae 20210708

- key: ferritin 
  description: ''
  synonyms:
    - 
  codes:
    LOINC:
      - 24373-3
      - 2276-4
  attributes:
    valid: #Need to be provided
      min: 0.0
      max: 5000.0
    reference: #Need to be provided
      min: 600.0
      max: 1800.0
    units: ng/ml
    source: '' #Need to be provided

- key: blasts_count
  description: 'reference range defaults to valid range for lack of reference range information'
  synonyms:
    - blasts [#/volume] in blood by manual count
    - blasts [#/volume] in blood
  codes:
    LOINC:
      - 708-8
      - 30376-8
  attributes:
    valid:
      min: 0.0
      max: 1000.0
    reference:
      min: 0.0
      max: 1000.0
    units: 1e3/mm3
    source: jcain, canoble 20220314

- key: blasts_percent
  description: 'reference range defaults to valid range for lack of reference range information'
  synonyms:
    - blasts/100 leukocytes in blood by manual count
    - blasts/100 leukocytes in blood
  codes:
    LOINC:
      - 709-6
      - 26446-5
  attributes:
    valid:
      min: 0.0
      max: 20.0
    reference:
      min: 0.0
      max: 20.0
    units: percent
    source: jcain, canoble 20220314